// ui/skill-md/mcp-setup.js — Steps 1-3: always-included MCP setup instructions
// These steps are universal for every SKILL.md regardless of which mods are selected.

export function buildStep1AndroidMCP() {
  var lines = [];
  lines.push('## Step 1 — Install and Configure the Android MCP Server');
  lines.push('');
  lines.push('> **Purpose:** The Android MCP server exposes on-device control tools (scrcpy, ADB, UI automation, screenshots, app management) to your AI agent. It is required for installing the patched APK, verifying changes on-device, and automating any runtime validation.');
  lines.push('');
  lines.push('### 1.1 Prerequisites');
  lines.push('');
  lines.push('- **Node.js** ≥ v18 installed on your host machine.');
  lines.push('- **ADB** (Android Debug Bridge) installed and on your `PATH`. Verify with `adb version`.');
  lines.push('- **scrcpy** installed (optional but strongly recommended — makes screenshot/tap/swipe 10-50× faster). Verify with `scrcpy --version`.');
  lines.push('- An **Android device or emulator** with **USB debugging** enabled (Settings → Developer Options → USB Debugging).');
  lines.push('- Connect the device via USB or WiFi ADB. Verify with `adb devices` — you should see a device serial.');
  lines.push('');
  lines.push('### 1.2 Install the Android MCP Server');
  lines.push('');
  lines.push('```bash');
  lines.push('# Clone or install the android-mcp package');
  lines.push('npm install -g android-mcp');
  lines.push('');
  lines.push('# Or if from source:');
  lines.push('git clone https://github.com/nicholasgasior/android-mcp.git');
  lines.push('cd android-mcp');
  lines.push('npm install && npm run build');
  lines.push('```');
  lines.push('');
  lines.push('### 1.3 Configure in Your AI IDE');
  lines.push('');
  lines.push('Add the Android MCP server to your IDE\'s MCP configuration file. For **Claude Code**, edit `~/.claude/mcp_servers.json` (or use `claude mcp add`). For **Google Antigravity IDE**, add it via Settings → MCP Servers. For **Cursor**, edit `.cursor/mcp.json`. For **VS Code (Cline/Roo Code)**, edit the extension\'s MCP settings.');
  lines.push('');
  lines.push('```json');
  lines.push('{');
  lines.push('  "mcpServers": {');
  lines.push('    "android": {');
  lines.push('      "command": "npx",');
  lines.push('      "args": ["-y", "android-mcp"],');
  lines.push('      "env": {');
  lines.push('        "ADB_PATH": "adb"');
  lines.push('      }');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('```');
  lines.push('');
  lines.push('> **If already installed:** Skip installation. Verify the server is running by checking that `device_list`, `screenshot`, and `app_install` tools are available in your AI agent\'s tool list.');
  lines.push('');
  lines.push('### 1.4 Available Android MCP Tools (Reference)');
  lines.push('');
  lines.push('| Tool | Description | Requires scrcpy Session? |');
  lines.push('|------|-------------|:---:|');
  lines.push('| `start_session` | Start a scrcpy session for fast input/screenshots | — (enables others) |');
  lines.push('| `stop_session` | Stop the active scrcpy session; falls back to ADB | — |');
  lines.push('| `device_list` | List connected Android devices (serial, state, model) | No |');
  lines.push('| `device_info` | Get model, Android version, screen size, SDK, battery | No |');
  lines.push('| `screen_on` / `screen_off` | Wake or sleep the device screen | No |');
  lines.push('| `connect_wifi` / `disconnect_wifi` | Enable/disable WiFi ADB | No |');
  lines.push('| `rotate_device` | Rotate screen orientation | Yes |');
  lines.push('| `expand_notifications` / `expand_settings` / `collapse_panels` | Control notification/settings panels | Yes |');
  lines.push('| `screenshot` | Capture screenshot as base64 image | No (faster with session) |');
  lines.push('| `screen_record_start` / `screen_record_stop` | Record screen video | No |');
  lines.push('| `swipe` | Swipe gesture from point A to B | No (faster with session) |');
  lines.push('| `drag_drop` | Drag-and-drop gesture (Android 8.0+) | No |');
  lines.push('| `input_text` | Type text into focused input field | No (faster with session) |');
  lines.push('| `key_event` | Send key events (HOME, BACK, ENTER, VOLUME_UP, etc.) | No |');
  lines.push('| `scroll` | Scroll at a position (dx/dy approx -1 to 1) | No |');
  lines.push('| `app_start` | Launch an app (supports `+` prefix to force-stop first) | No (faster with session) |');
  lines.push('| `app_stop` | Force-stop an app | No |');
  lines.push('| `app_install` | Install an APK from host to device | No |');
  lines.push('| `app_uninstall` | Uninstall an app from device | No |');
  lines.push('| `app_list` | List installed packages (filter by name/system/third-party) | No |');
  lines.push('| `app_current` | Get foregrounded app package + activity | No |');
  lines.push('| `clipboard_get` / `clipboard_set` | Read/write device clipboard | No (faster with session) |');
  lines.push('| `ui_dump` | Dump full UI hierarchy as XML | No |');
  lines.push('| `ui_find_element` | Find UI elements by text/ID/class/description → tap coords | No |');
  lines.push('| `shell_exec` | Execute arbitrary ADB shell command | No |');
  lines.push('| `file_push` / `file_pull` | Push/pull files between host and device | No |');
  lines.push('| `file_list` | List directory contents on device | No |');
  lines.push('| `start_video_stream` / `stop_video_stream` | MJPEG video stream via ffplay | Auto-starts session |');
  lines.push('');
  lines.push('### 1.5 Verify the Android MCP Server');
  lines.push('');
  lines.push('After configuration, **reload/refresh your AI IDE** so it discovers the new MCP server. Then verify:');
  lines.push('');
  lines.push('1. Run `device_list` — confirm your device appears.');
  lines.push('2. Run `start_session` — confirm scrcpy session starts (optional but recommended).');
  lines.push('3. Run `screenshot` — confirm a base64 image is returned.');
  lines.push('');
  lines.push('If any tool is missing or errors, refer to the Android MCP server documentation and ensure ADB/scrcpy are correctly installed and on your PATH.');
  lines.push('');
  return lines.join('\n');
}

export function buildStep2ApkMCP() {
  var lines = [];
  lines.push('## Step 2 — Install and Configure the APK MCP Server (MT Manager)');
  lines.push('');
  lines.push('> **Purpose:** The APK MCP server provides deep APK inspection, editing, and building tools. It runs inside the **MT Manager** Android app and exposes tools for reading/writing smali, AXML, resources.arsc, and building signed APKs. This is the core tool for applying modifications.');
  lines.push('');
  lines.push('### 2.1 Prerequisites');
  lines.push('');
  lines.push('- **MT Manager** app installed on your Android device (available from its official source).');
  lines.push('- The **APK MCP plugin/module** installed within MT Manager.');
  lines.push('- A signing key configured in APK MCP settings (for `mt_apk_build`).');
  lines.push('');
  lines.push('### 2.2 Install APK MCP in MT Manager');
  lines.push('');
  lines.push('1. Open **MT Manager** on your Android device.');
  lines.push('2. Navigate to the APK MCP module/plugin section.');
  lines.push('3. Install or enable the APK MCP server module.');
  lines.push('4. Configure the signing key in APK MCP settings (this key will be used by `mt_apk_build` to sign output APKs).');
  lines.push('');
  lines.push('### 2.3 Connect APK MCP to Your AI IDE');
  lines.push('');
  lines.push('The APK MCP server runs on-device via MT Manager. Add it to your AI IDE\'s MCP configuration:');
  lines.push('');
  lines.push('```json');
  lines.push('{');
  lines.push('  "mcpServers": {');
  lines.push('    "apk-mcp": {');
  lines.push('      "command": "<mt-manager-mcp-bridge-command>",');
  lines.push('      "args": [],');
  lines.push('      "env": {}');
  lines.push('    }');
  lines.push('  }');
  lines.push('}');
  lines.push('```');
  lines.push('');
  lines.push('> **Note:** The exact connection method depends on your MT Manager version. Refer to MT Manager\'s APK MCP documentation for the bridge command and connection details. The server must be running and accessible from your AI agent.');
  lines.push('');
  lines.push('### 2.4 Available APK MCP Tools (Reference)');
  lines.push('');
  lines.push('| Tool | Description | Key Inputs |');
  lines.push('|------|-------------|------------|');
  lines.push('| `mt_apk_open` | Open a read-only APK workspace. **Use first.** | `path`, `temporary` |');
  lines.push('| `mt_apk_list_available_apks` | List APK targets that `mt_apk_open` can open | `prefix`, `limit` |');
  lines.push('| `mt_apk_list` | Page through ZIP entries, dex classes, or resource table entries | `workspaceId`, `view`, `prefix`, `limit` |');
  lines.push('| `mt_apk_outline_class` | Read one dex class outline (fields + methods) | `workspaceId`, `editSessionId`, `locator` |');
  lines.push('| `mt_apk_read_text` | Read text from a known locator (zip_entry, axml, smali) | `workspaceId`, `editSessionId`, `locator` |');
  lines.push('| `mt_apk_read_zip_bytes` | Read raw hex bytes from a zip_entry locator | `workspaceId`, `editSessionId`, `locator` |');
  lines.push('| `mt_apk_read_resource` | Batch-read resources.arsc values by exact locators + variants | `workspaceId`, `editSessionId`, `reads[]`, budget fields |');
  lines.push('| `mt_apk_search` | Search APK structures (overview, smali, dex strings, resource paths) | `workspaceId`, `editSessionId`, `target`, `query`, `queryType`, etc. |');
  lines.push('| `mt_apk_xref_dex` | Find incoming instruction references for a dex locator | `workspaceId`, `editSessionId`, `locator`, `methodResolution`, `limit` |');
  lines.push('| `mt_apk_xref_resource` | Find stable references to a resource ID across dex/axml/resource_table | `workspaceId`, `editSessionId`, `resourceId`, `scopes[]`, `limit` |');
  lines.push('| `mt_apk_continue` | Continue a paged result (copy nextCursor from nextActions) | `workspaceId`, `editSessionId`, `nextCursor`, `limit` |');
  lines.push('| `mt_apk_edit_open` | Open an isolated edit session from a workspace. **Use before editing.** | `workspaceId` |');
  lines.push('| `mt_apk_edit_text` | Edit text in an APK edit session (smali, AXML, zip_entry) | `workspaceId`, `editSessionId`, `edits[]` (mode, matchText, writeText) + targetVersion |');
  lines.push('| `mt_apk_edit_resource` | Edit resources.arsc values using complete valueXml | `workspaceId`, `editSessionId`, `edits[]` (locator, variant, targetVersion, valueXml) |');
  lines.push('| `mt_apk_edit_check` | Check edit session health and buildability (optional pre-build check) | `workspaceId`, `editSessionId`, `runBuildChecks` |');
  lines.push('| `mt_apk_build` | Build the edit session into a new signed APK. **Final step.** | `workspaceId`, `editSessionId`, `outputName`, `overwrite` |');
  lines.push('| `mt_apk_close` | Clean up a temporary workspace (only for temporary=true workspaces) | `workspaceId` |');
  lines.push('');
  lines.push('### 2.5 Verify the APK MCP Server');
  lines.push('');
  lines.push('After configuration, **reload/refresh your AI IDE** so it discovers the new MCP server. Then verify:');
  lines.push('');
  lines.push('1. Run `mt_apk_list_available_apks` — confirm it returns APK targets.');
  lines.push('2. Run `mt_apk_open` with a test APK path — confirm it returns a workspaceId.');
  lines.push('');
  return lines.join('\n');
}

export function buildStep3ReloadAndVerify() {
  var lines = [];
  lines.push('## Step 3 — Reload AI IDE / Refresh MCP Servers');
  lines.push('');
  lines.push('> **Purpose:** After installing both MCP servers (Android MCP and APK MCP), your AI IDE must reload to discover and register the new tools. This step ensures all tools from both servers are available before proceeding.');
  lines.push('');
  lines.push('### 3.1 Reload Your AI IDE');
  lines.push('');
  lines.push('Depending on your IDE:');
  lines.push('');
  lines.push('- **Claude Code:** Run `/mcp` to list MCP servers, or restart Claude Code to reload all servers.');
  lines.push('- **Google Antigravity IDE:** Go to Settings → MCP Servers → click "Refresh" or restart the IDE.');
  lines.push('- **Cursor:** Restart Cursor or reload the window (Command Palette → "Reload Window").');
  lines.push('- **VS Code (Cline/Roo Code):** Reload the window or restart the extension.');
  lines.push('- **Other IDEs:** Follow the IDE\'s documentation for refreshing/reloading MCP server connections.');
  lines.push('');
  lines.push('### 3.2 Verify Both MCP Servers Are Connected');
  lines.push('');
  lines.push('After reloading, verify that tools from BOTH servers are available:');
  lines.push('');
  lines.push('1. **Android MCP tools:** Confirm `device_list`, `screenshot`, `app_install`, `start_session` are listed.');
  lines.push('2. **APK MCP tools:** Confirm `mt_apk_open`, `mt_apk_edit_open`, `mt_apk_edit_text`, `mt_apk_build` are listed.');
  lines.push('');
  lines.push('> **⚠️ Important:** Do not proceed to Step 4 until both MCP servers are verified as connected and their tools are available in your AI agent. Missing tools will cause modification steps to fail.');
  lines.push('');
  return lines.join('\n');
}
